For Pancakes
2 egg yolks
2 egg whites, whipped
3 tablespoons sugar
1 ⅓ cups milk (315 mL), more if the batter is too thick
3 tablespoons butter, melted
1 teaspoon vanilla extract
1 ½ cups flour (185 g)
¼ cup cocoa powder (30 g)
2 ½ teaspoons baking powder
3 ½ oz chocolate (105 g), finely chopped
1 tablespoon butter, or oil for cooking


 For Chocolate Ganache 
1 cup heavy cream (240 mL)
8 oz chocolate chips (175 g)
raspberry, for garnish